config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, controller: :users, only: %i[index show]

  resources :games, only: %i[create show] do
    member do
      put 'help' # помощь зала
      put 'answer' # ответ на текущий вопрос
      put 'take_money' #  игрок берет деньги
    end
  end
  #
  # что эквивалентно:
  # get '/games/:id', to: 'games#show', as: :game
  # post '/games', to: 'games#create', as: :games
  # put '/games/:id/take_money', to: 'games#take_money', as: :take_money_game
  # put '/games/:id/answer', to: 'games#answer', as: :answer_game
  # put '/games/:id/help', to: 'games#help', as: :help_game

  # и эквивалентно:
  # get '/games/:id', action: :show, controller: 'games'
  # post '/games', action: :create, controller: 'games'
  # put '/games/:id/take_money', action: :take_money, controller: 'games', as: :take_money_game
  # put '/games/:id/answer', action: :answer, controller: 'games', as: :answer_game
  # put '/games/:id/help', action: :help, controller: 'games', as: :help_game

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: %i[new create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title') %></title>
    <meta charset="utf-8">

    <%# прочие стили %>
    <script src="http://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>

    <div class="navbar navbar-light bg-custom">
      <div class="container">
        <%= link_to t('.title'), root_path, class: 'navbar-brand text-light' %>
        <% if user_signed_in? %>
          <div class="navbar-form navbar-right">

            <% if current_user.is_admin? %>
              <%= link_to t('.admin'), rails_admin_path, target: '_self', class: 'btn navbar-btn btn-danger btn-xs' %>
              <%= link_to t('.add_new_questions'), new_questions_path, class: 'btn navbar-btn btn-warning btn-xs' %>
            <% end %>


            <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                        user_path(current_user),
                        class: 'btn text-light'
            %>
            <%= link_to t('.new_game'), games_path, method: :post, class: 'btn btn-success' %>
            <%= link_to t('.log_out'), destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %>
          </div>
        <% else %>
          <div class="navbar-form navbar-right">
            <%= link_to t('.log_in'), new_user_session_path, class: 'btn text-light' %>
            <%= link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="row mt-4">
        <div class="col-lg-12">
          <%= flash_messages %>
          <%= yield %>
        </div>
      </div>

      <footer class="container mt-auto d-flex flex-wrap justify-content-between align-items-center py-3  mb-0">

        <div class="col-md-4 d-flex align-items-center">
          <a class="link-light text-decoration-none" href="https://vk.com/professornemo">
            <p class="pt-3">&copy;
              <%= t('.goodprogrammer') %></p>
          </a>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
          <li class="ms-3">
            <a href="https://github.com/ProfessorNemo"><img src="<%= asset_path('gh.png') %>" class="bi" width="30" height="30"></a>
          </li>
        </ul>
      </footer>
    </div>

  </body>
</html>